// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFErRsXNjJU4_orSehETE9JBQ-O_kk5Dg',
    appId: '1:166294355979:web:b5f05f931fa87e2a5a070e',
    messagingSenderId: '166294355979',
    projectId: 'inspire-admin-portal',
    authDomain: 'inspire-admin-portal.firebaseapp.com',
    storageBucket: 'inspire-admin-portal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlHsdPgxFqgVi8-ZgdcwmRzI0a50-8hAA',
    appId: '1:166294355979:android:3b8aa2d7b154efe85a070e',
    messagingSenderId: '166294355979',
    projectId: 'inspire-admin-portal',
    storageBucket: 'inspire-admin-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3i3SO3NUgo-PExD8jSL8gI5ZZhfD4ztI',
    appId: '1:166294355979:ios:d5069870d859a8275a070e',
    messagingSenderId: '166294355979',
    projectId: 'inspire-admin-portal',
    storageBucket: 'inspire-admin-portal.firebasestorage.app',
    iosBundleId: 'com.example.inspireAdminPortal',
  );
}
